---
# Include variable definitions
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution }}.yml"
      - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags:
    - docker-registry

# Run docker image
- name: run docker image
  docker_container:
    name: "{{ docker_registry_service_name }}"
    image: "{{ docker_registry_image }}"
    published_ports:
      - "{{ docker_registry_service_port }}:{{ docker_registry_service_port }}"
    state: "{{ docker_registry_service_status }}"
    restart_policy: "{{ docker_registry_service_restart_policy }}"
    pull: "{{ docker_registry_image_pull }}"
    volumes:
      - "{{ docker_registry_storage_path }}:{{ docker_registry_storage_volume }}"
  become: yes
  tags:
    - docker-registry

# Set up service file
#- name: configure docker-registry
#  template: >
#    src="{{ docker_registry_conf_template }}"
#    dest="{{ docker_registry_conf_path }}"
#  become: no
#  when: docker-registry_conf_path is defined
#  tags:
#    - "docker-registry"
#    - "docker-registry_conf"
#  notify:
#    - restart docker-registry

# Manage service
#- name: manage docker-registry services
#  service: >
#    name="{{ docker_registry_service_name }}"
#    state="{{ docker_registry_service_status }}"
#  become: yes
#  when: docker-registry_service_name is defined
#  tags:
#    - docker-registry
#    - docker-registry_service
#  notify:
#    - restart docker-registry
